import type {
	ObjectColumn,
	ObjectConstraint,
	ObjectDependent,
	ObjectDescribeResult,
	ObjectGrant,
	ObjectIndex,
	ObjectTrigger,
} from "@datagripe/contracts";
import type { SQL } from "bun";
import {
	formatAgo,
	formatBytes,
	formatCount,
	reconstructCreateTable,
	statTiles,
} from "../object/format";
import { POSTGRES_TABLE_DIALECT, TableRequestError } from "../table/builder";
import type { ObjectRequest, TableLimits } from "../types";

/**
 * PostgreSQL object view (docs/spec/object-view.md). Every tab is a
 * catalog read, so they all run in one read-only transaction with a
 * statement timeout and are returned together — switching tabs should
 * not feel like loading a page.
 */

const COLUMNS_SQL = `
	SELECT a.attname AS name,
		format_type(a.atttypid, a.atttypmod) AS data_type,
		NOT a.attnotnull AS nullable,
		CASE a.attidentity
			WHEN 'a' THEN 'generated always as identity'
			WHEN 'd' THEN 'generated by default as identity'
			ELSE pg_get_expr(d.adbin, d.adrelid)
		END AS default_expr,
		a.attidentity <> '' AS is_identity,
		COALESCE(pk.is_pk, false) AS primary_key,
		col_description(c.oid, a.attnum) AS comment
	FROM pg_attribute a
	JOIN pg_class c ON c.oid = a.attrelid
	JOIN pg_namespace n ON n.oid = c.relnamespace
	LEFT JOIN pg_attrdef d ON d.adrelid = c.oid AND d.adnum = a.attnum
	LEFT JOIN (
		SELECT conrelid, unnest(conkey) AS attnum, true AS is_pk
		FROM pg_constraint WHERE contype = 'p'
	) pk ON pk.conrelid = c.oid AND pk.attnum = a.attnum
	WHERE n.nspname = $1 AND c.relname = $2
		AND a.attnum > 0 AND NOT a.attisdropped
	ORDER BY a.attnum`;

// Key columns come from pg_get_indexdef per position rather than from
// slicing the whole definition: a partial index's WHERE clause has its
// own parentheses and would be swallowed by any regex over the text.
const INDEXES_SQL = `
	SELECT i.relname AS name,
		am.amname AS method,
		(
			SELECT string_agg(
				pg_get_indexdef(x.indexrelid, k, true)
					-- indoption is a 0-based int2vector; bit 0 is DESC.
					|| CASE WHEN (x.indoption[k - 1] & 1) = 1 THEN ' DESC' ELSE '' END,
				', ' ORDER BY k)
			FROM generate_series(1, x.indnkeyatts) k
		) AS columns,
		x.indisunique AS is_unique,
		x.indisprimary AS is_primary,
		pg_relation_size(i.oid) AS size_bytes,
		pg_get_indexdef(x.indexrelid) AS definition,
		EXISTS (
			SELECT 1 FROM pg_constraint con WHERE con.conindid = x.indexrelid
		) AS from_constraint
	FROM pg_index x
	JOIN pg_class i ON i.oid = x.indexrelid
	JOIN pg_class t ON t.oid = x.indrelid
	JOIN pg_namespace n ON n.oid = t.relnamespace
	JOIN pg_am am ON am.oid = i.relam
	WHERE n.nspname = $1 AND t.relname = $2
	ORDER BY x.indisprimary DESC, i.relname`;

const CONSTRAINTS_SQL = `
	SELECT con.conname AS name,
		CASE con.contype
			WHEN 'p' THEN 'primary key'
			WHEN 'f' THEN 'foreign key'
			WHEN 'u' THEN 'unique'
			WHEN 'c' THEN 'check'
			WHEN 'x' THEN 'exclusion'
			ELSE con.contype::text
		END AS type,
		pg_get_constraintdef(con.oid) AS definition
	FROM pg_constraint con
	JOIN pg_class c ON c.oid = con.conrelid
	JOIN pg_namespace n ON n.oid = c.relnamespace
	WHERE n.nspname = $1 AND c.relname = $2
	ORDER BY
		CASE con.contype WHEN 'p' THEN 0 WHEN 'u' THEN 1 WHEN 'f' THEN 2 ELSE 3 END,
		con.conname`;

// tgtype is a bitmask: 2 before, 4 insert, 8 delete, 16 update,
// 32 truncate, 64 instead of.
const TRIGGERS_SQL = `
	SELECT t.tgname AS name,
		CASE
			WHEN (t.tgtype & 64) <> 0 THEN 'instead of'
			WHEN (t.tgtype & 2) <> 0 THEN 'before'
			ELSE 'after'
		END AS timing,
		concat_ws(', ',
			CASE WHEN (t.tgtype & 4) <> 0 THEN 'insert' END,
			CASE WHEN (t.tgtype & 8) <> 0 THEN 'delete' END,
			CASE WHEN (t.tgtype & 16) <> 0 THEN 'update' END,
			CASE WHEN (t.tgtype & 32) <> 0 THEN 'truncate' END
		) AS events,
		p.proname || '()' AS action,
		t.tgenabled <> 'D' AS enabled
	FROM pg_trigger t
	JOIN pg_class c ON c.oid = t.tgrelid
	JOIN pg_namespace n ON n.oid = c.relnamespace
	JOIN pg_proc p ON p.oid = t.tgfoid
	WHERE n.nspname = $1 AND c.relname = $2 AND NOT t.tgisinternal
	ORDER BY t.tgname`;

const GRANTS_SQL = `
	SELECT grantee,
		string_agg(lower(privilege_type), ', ' ORDER BY privilege_type) AS privileges,
		min(grantor) AS grantor
	FROM information_schema.role_table_grants
	WHERE table_schema = $1 AND table_name = $2
	GROUP BY grantee
	ORDER BY grantee`;

const STATISTICS_SQL = `
	SELECT c.reltuples::bigint AS reltuples,
		s.n_live_tup,
		s.n_dead_tup,
		GREATEST(s.last_vacuum, s.last_autovacuum) AS last_vacuum,
		GREATEST(s.last_analyze, s.last_autoanalyze) AS last_analyze,
		pg_table_size(c.oid) AS heap_bytes,
		pg_indexes_size(c.oid) AS index_bytes,
		pg_total_relation_size(c.oid) AS total_bytes
	FROM pg_class c
	JOIN pg_namespace n ON n.oid = c.relnamespace
	LEFT JOIN pg_stat_all_tables s ON s.relid = c.oid
	WHERE n.nspname = $1 AND c.relname = $2`;

const VIEW_DDL_SQL = `
	SELECT pg_get_viewdef(c.oid, true) AS definition
	FROM pg_class c
	JOIN pg_namespace n ON n.oid = c.relnamespace
	WHERE n.nspname = $1 AND c.relname = $2`;

/** Rewrite dependencies (views built on this relation). */
const DEPENDENT_VIEWS_SQL = `
	SELECT DISTINCT
		CASE dep.relkind WHEN 'm' THEN 'materialized view' ELSE 'view' END AS kind,
		dn.nspname || '.' || dep.relname AS name
	FROM pg_depend d
	JOIN pg_rewrite rw ON rw.oid = d.objid
	JOIN pg_class dep ON dep.oid = rw.ev_class
	JOIN pg_namespace dn ON dn.oid = dep.relnamespace
	JOIN pg_class src ON src.oid = d.refobjid
	JOIN pg_namespace sn ON sn.oid = src.relnamespace
	WHERE sn.nspname = $1 AND src.relname = $2 AND dep.oid <> src.oid
	ORDER BY name`;

/** Foreign keys pointing at this table — what a DROP would cascade to. */
const DEPENDENT_KEYS_SQL = `
	SELECT 'foreign key' AS kind,
		cn.nspname || '.' || child.relname || ' (' || con.conname || ')' AS name
	FROM pg_constraint con
	JOIN pg_class child ON child.oid = con.conrelid
	JOIN pg_namespace cn ON cn.oid = child.relnamespace
	JOIN pg_class parent ON parent.oid = con.confrelid
	JOIN pg_namespace pn ON pn.oid = parent.relnamespace
	WHERE con.contype = 'f' AND pn.nspname = $1 AND parent.relname = $2
	ORDER BY name`;

type Row = Record<string, unknown>;

function text(value: unknown): string {
	return value === null || value === undefined ? "" : String(value);
}

function nullableText(value: unknown): string | null {
	return value === null || value === undefined ? null : String(value);
}

function nullableNumber(value: unknown): number | null {
	const parsed = Number(value);
	return value === null || value === undefined || !Number.isFinite(parsed)
		? null
		: parsed;
}

export async function describePostgresObject(
	client: SQL,
	request: ObjectRequest,
	limits: TableLimits,
): Promise<ObjectDescribeResult> {
	const reserved = await client.reserve();
	try {
		await reserved.unsafe(
			`SET statement_timeout = ${Math.max(1, Math.floor(limits.timeoutMs))}`,
		);
		await reserved.unsafe("BEGIN READ ONLY");
		try {
			const query = async (sql: string): Promise<Row[]> =>
				(await reserved.unsafe(sql, [request.schema, request.name])) as Row[];

			// Sequential, not Promise.all: these share one reserved connection
			// inside an open transaction, and a single backend runs one
			// statement at a time regardless of how many we dispatch.
			const columnRows = await query(COLUMNS_SQL);
			const indexRows = await query(INDEXES_SQL);
			const constraintRows = await query(CONSTRAINTS_SQL);
			const triggerRows = await query(TRIGGERS_SQL);
			const grantRows = await query(GRANTS_SQL);
			const statRows = await query(STATISTICS_SQL);
			const dependentViewRows = await query(DEPENDENT_VIEWS_SQL);
			const dependentKeyRows =
				request.kind === "table" ? await query(DEPENDENT_KEYS_SQL) : [];

			if (columnRows.length === 0) {
				throw new TableRequestError(
					`'${request.schema}.${request.name}' was not found`,
				);
			}

			const columns: ObjectColumn[] = columnRows.map((row) => ({
				name: text(row.name),
				dataType: text(row.data_type),
				nullable: row.nullable === true,
				defaultExpr: nullableText(row.default_expr),
				primaryKey: row.primary_key === true,
				comment: nullableText(row.comment),
			}));
			// `generated … as identity` is a column clause, not a DEFAULT, so
			// the DDL builder is told which columns spell it that way.
			const identityColumns = new Set(
				columnRows
					.filter((row) => row.is_identity === true)
					.map((row) => text(row.name)),
			);

			const indexes: ObjectIndex[] = indexRows.map((row) => ({
				name: text(row.name),
				method: text(row.method),
				columns: text(row.columns),
				unique: row.is_unique === true,
				primary: row.is_primary === true,
				sizeBytes: nullableNumber(row.size_bytes),
			}));

			const constraints: ObjectConstraint[] = constraintRows.map((row) => ({
				name: text(row.name),
				type: text(row.type),
				definition: text(row.definition),
			}));

			const triggers: ObjectTrigger[] = triggerRows.map((row) => ({
				name: text(row.name),
				timing: text(row.timing),
				events: text(row.events),
				action: text(row.action),
				enabled: row.enabled === true,
			}));

			const grants: ObjectGrant[] = grantRows.map((row) => ({
				grantee: text(row.grantee),
				privileges: text(row.privileges),
				grantor: nullableText(row.grantor),
			}));

			const stat = statRows[0] ?? {};
			const liveRows = nullableNumber(stat.n_live_tup);
			const reltuples = nullableNumber(stat.reltuples);
			// Both numbers are estimates that go stale differently: reltuples
			// is the planner's, refreshed by ANALYZE, and is -1 before the
			// first one; n_live_tup is the stats collector's and reads 0 until
			// it flushes. Prefer reltuples so the header agrees with the table
			// view's footer, which estimates from the same column.
			const rowEstimate =
				reltuples !== null && reltuples >= 0 ? reltuples : liveRows;
			const deadRows = nullableNumber(stat.n_dead_tup);
			const deadRatio =
				deadRows !== null && liveRows !== null && liveRows + deadRows > 0
					? `${((deadRows / (liveRows + deadRows)) * 100).toFixed(1)}%`
					: null;

			const statistics = statTiles([
				// Labelled as an estimate because that is what it is — there is
				// no cheap exact count, and the table view's footer is where an
				// exact number belongs.
				["rows (estimated)", formatCount(rowEstimate)],
				["heap", formatBytes(nullableNumber(stat.heap_bytes))],
				["indexes", formatBytes(nullableNumber(stat.index_bytes))],
				["total", formatBytes(nullableNumber(stat.total_bytes))],
				["dead tuples", deadRatio],
				["last vacuum", formatAgo(nullableText(stat.last_vacuum))],
				["last analyze", formatAgo(nullableText(stat.last_analyze))],
			]);

			let ddl: string | null = null;
			let ddlReconstructed = false;
			if (request.kind === "view") {
				const viewRows = await query(VIEW_DDL_SQL);
				const definition = nullableText(viewRows[0]?.definition);
				ddl =
					definition === null
						? null
						: `create or replace view ${POSTGRES_TABLE_DIALECT.quote(
								request.schema,
							)}.${POSTGRES_TABLE_DIALECT.quote(request.name)} as\n${definition}`;
			} else {
				ddlReconstructed = true;
				ddl = reconstructCreateTable({
					quote: POSTGRES_TABLE_DIALECT.quote,
					schema: request.schema,
					name: request.name,
					columns,
					constraints,
					bareDefaults: identityColumns,
					// An index that backs a constraint is emitted by the
					// constraint, so repeating it here would produce DDL that
					// creates the same index twice.
					indexStatements: indexRows
						.filter((row) => row.from_constraint !== true)
						.map((row) => `${text(row.definition)};`),
				});
			}

			const dependents: ObjectDependent[] = [
				...dependentViewRows,
				...dependentKeyRows,
			].map((row) => ({ kind: text(row.kind), name: text(row.name) }));

			return {
				schema: request.schema,
				name: request.name,
				kind: request.kind,
				rowEstimate,
				// Neither source is exact, so the header always says so.
				estimated: rowEstimate !== null,
				columns,
				indexes,
				constraints,
				triggers,
				grants,
				statistics,
				ddl,
				unsupported: [],
				ddlReconstructed,
				dependents,
			};
		} finally {
			await reserved.unsafe("ROLLBACK").catch(() => {});
		}
	} finally {
		reserved.release();
	}
}
